### ISSUE TITLE
Intercomponent spacing in PCB

### ISSUE THREAD

**Issue by Adhithya03** [Adhithya03/FOC_DOCS#15]

**Comment by Anabhayan** [comment]
MATAN PAZI 
GIT LINK [https://github.com/MatanPazi/VFD/blob/main/VFD_Prototype_Schematics.pdf](url)
HW VIDEO [https://www.youtube.com/watch?v=wUGCEtSXV1I&t=431s&ab_channel=MatanPazi](url)

**Comment by Adhithya03** [comment]
https://www.youtube.com/watch?v=wsU6mhyBQI0

https://www.electronics-lab.com/project/600v-30a-ipm-module-carrier-board-for-variable-frequency-drive-vfd/
