### ISSUE TITLE
Rcsc value

### ISSUE THREAD

**Issue by Adhithya03** [Adhithya03/FOC_DOCS#19]
![image](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/61418f8c-2468-4cc9-96c7-f4f7e824ce30)

are we sure it's 0Ohm shall we freeeze it?

**Comment by Anabhayan** [comment]
![IMG_6192](https://github.com/Adhithya03/FOC_DOCS/assets/114506427/aa20a13c-6aa6-4172-862b-5f8e83c142a0)
Rcsc is not included in application circuit

**Comment by Anabhayan** [comment]
So, remove Rcsc from pcb layout
