### ISSUE TITLE
At high and low frequency what is drop across Capcitor and resistor

### ISSUE THREAD

**Issue by Adhithya03** [Adhithya03/FOC_DOCS#22]

**Comment by Adhithya03** [comment]
![image](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/9b0dfcbc-3580-4b78-9d06-2ea482ecebb3)


![WhatsApp Image 2024-03-19 at 20 19 30_ac967202](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/f755020e-933c-44da-9fae-32959f435901)

**Comment by Anabhayan** [comment]
[https://www.digikey.com/en/resources/conversion-calculators/conversion-calculator-low-pass-and-high-pass-filter](url)
