### ISSUE TITLE
Current reading A phase and B phase 

### ISSUE THREAD

**Issue by Adhithya03** [Adhithya03/FOC_DOCS#33]
- https://chatkit.app/s/79xoh6fffoiwh1l

**Comment by Adhithya03** [comment]
![image](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/41e68b7f-db90-45fd-a4fb-c72ddc1ff446)

**Comment by Adhithya03** [comment]
![image](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/eb4d8b4b-be61-454f-8ad5-d5c937dc135a)

**Comment by Adhithya03** [comment]
![image](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/d80c25c2-3cbc-4c04-b85c-c3d607b4030d)

**Comment by Anabhayan** [comment]
Let's close it after we buy an accurate sensor and measure reliably from it
