### ISSUE TITLE
ADC ACK. Window calc.

### ISSUE THREAD

**Issue by Adhithya03** [Adhithya03/FOC_DOCS#38]
![image](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/eaeb1b17-c222-480d-ad19-d5025c0b99c5)
![image](https://github.com/Adhithya03/FOC_DOCS/assets/77617084/4016ef5a-9ca5-464b-b0ea-d3ca1d7b6a21)

@Anabhayan  help me calculate the ADC acquisition window.

**Comment by Adhithya03** [comment]
@Anabhayan 

[ADC techincal Reference.pdf](https://github.com/Adhithya03/FOC_DOCS/files/14920939/ADC.techincal.Reference.pdf)

Refer this for knowing about ADC acquisition window.

**Comment by Anabhayan** [comment]
add the image containing parameter values from datasheet.
